version: "3.8"

services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-br6%c=w8syu*esf3curlo7p7inlc6f4=#li(y8b*_lbnpi2r6a
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
